### ISSUE TITLE
亻尔 女子

### ISSUE THREAD

**Issue by TotoWang-hhh** [teapotcn/EMDL-Project#1]
您貌似给我的某个项目点了个star，我是通过那里顺着找过来的（我确实有点进每个star和follow我的人的主页然后翻个底朝天的习惯）

这似乎是一个针对网易云的音乐下载器，我简单看了下repo里的文件内容。

1. 通过外链只能下载到非常有限的歌曲
2. 不要随意在commit里祖安，或许可以写写你对代码做了什么，或者索性不填用默认

**Comment by teapotcn** [comment]
这是一个已被弃用的GitHub小号（主号是@Lafcadia），代码是四五年前写的（三年前与其他项目一并上传），准确来说是复制的网上的。
我非常喜欢您的 music_down 项目（据说最近停更了？），虽然出于个人平时实用改用了you-get。
其实本来有针对QQ音乐和酷我音乐的外链解析下载，后来由于QQ音乐改了算法懒得做了，所以就摆了，这两个也就没做。

**Comment by teapotcn** [comment]
此外，我无法改变很久以前的commit记录，我自己也比较后悔在commit里祖安了，请原谅。
